server:
  context-path: /
  port: 8888
#显示debug日志信息
debug: false
##演示自动配置
hello: 
  msg: yanwei
  show: true
#是否启用aop拦截日志存储mongo
enableAop: 
  storeMongo: false

spring:
  data: 
   #mongodb:
    #  uri: mongodb://root:root@192.168.163.128/yan?authSource=admin&authMechanism=MONGODB-CR
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yanwei.remote.com:60336/test?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=utf8;useSSL=true
    username: root
    password: p@ssw0rd
  jpa: 
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
  redis:  #redis配置
    database: 1 #  数据库索引
    host: 123.207.86.126
    port: 6379
#    password: Jbinfo@E12349
lifeCycle:  signal