server:
  context-path: /
  port: 8888
#显示debug日志信息
debug: false
##演示自动配置
hello: 
  msg: yanwei
  show: true
#是否启用aop拦截日志存储mongo
enableAop: 
  storeMongo: false
spring: 
  data: 
   #mongodb:
    #  uri: mongodb://root:root@192.168.163.128/yan?authSource=admin&authMechanism=MONGODB-CR
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yanwei.remote.com:60360/test?useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=utf8;useSSL=true
    username: root
    password: p@ssw0rd
  jpa: 
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
  redis:  #redis配置
    database: 0 #  数据库索引
    host: yanwei.remote.com
    port: 6379
    password: Rs2017!@#jbinfo123456
    pool: #    链接池
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0
lifeCycle:  testLifeCycle